server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /team1 {
        alias /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        proxy_pass http://localhost:80/team1/assets/;
    }

    location /team1/assets/ {
        root /usr/share/nginx/html/assets/;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
